### ISSUE TITLE
Cleanup taking minutes.

### ISSUE THREAD

**Issue by ArtoV** [devgeniem/gdev#25]
`gdev up` gave me a following error:
`Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose/cli/main.py", line 61, in main
  File "compose/cli/main.py", line 113, in perform_command
  File "contextlib.py", line 35, in __exit__
  File "compose/cli/errors.py", line 56, in handle_connection_errors
TypeError: log_timeout_error() takes exactly 1 argument (0 given)
docker-compose returned -1`

After that error I ran: `gdev cleanup`and console has shown `Removing exited docker containers...` for minutes.

**Comment by onnimonni** [comment]
Have you tried to restart `docker for mac` or your computer?

`gdev cleanup` is quite experimental, and you don't usually need it. It's for cleaning cached container images and exited containers.

**Comment by ArtoV** [comment]
The problem was with my Docker for mac. It was somehow stuck, good old restarting the computer helped.
